# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='produit',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
