# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='auteur',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='commentaire',
        ),
    ]
