# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('dateNaiss', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
                ('codePostal', models.IntegerField()),
                ('ville', models.CharField(max_length=255)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panier.Panier')),
            ],
        ),
    ]
