# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('code_postal', models.PositiveIntegerField()),
                ('ville', models.CharField(max_length=50)),
                ('produit', models.ManyToManyField(to='produit.Produit')),
            ],
        ),
    ]
