# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='total'),
        ),
    ]
